project:
  type: website
  output-dir: docs

website:
  title: "Caroline Cognot"
  favicon: assets/chicken_1.png # NOTE: that the `favicon` is a `website` level option (not under `navbar`)

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Research
    right: 
      - text: CV
        icon: file-earmark-pdf
        href: assets/CV_fev26.pdf
        target: _blank
      - icon: github # add icons as navbar buttons
        href: https://github.com/caroline-cognot
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/caroline-cognot-591969196/
        target: _blank
      - icon: envelope
        menu:
        - text: AgroParisTech (main adress)
          href: mailto:caroline.cognot@agroparistech.fr
        - text: EDF (secondary adress)
          href: mailto:caroline.cognot@edf.fr
format:
  html:
    theme: styles.scss
    toc: true

editor: visual

